slam_toolbox:
  ros__parameters:
    publish_tf: true
    use_sim_time: false
    mode: mapping

    # 2. Frame IDs (ชื่อระบบพิกัด)
    map_frame: map
    odom_frame: odom
    base_frame: base_link

    # 3. คุณสมบัติของแผนที่
    resolution: 0.01
    map_start_pose: [0.0, 0.0, 0.0]

    # 4. การจัดการข้อมูล Lidar และอัตราการอัปเดต
    transform_timeout: 0.5
    transform_publish_period: 0.05
    map_update_interval: 0.05
    minimum_time_interval: 0.05

    # 5. การกรองข้อมูล Lidar
    max_laser_range: 8.0
    minimum_range: 0.1
    scan_buffer_maximum_scan_distance: 8.5

    # 6. Topic ที่ใช้
    scan_topic: scan
    odom_topic: /odom

    # 7. การตั้งค่าขั้นสูง (สำคัญในการแก้ Drift)
    do_loop_closing: true
    #use_pose_extrapolator: true
    #solver_plugin: solver_plugins::CeresSolver
    #ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    #ceres_preconditioner: SCHUR_JACOBI

    link_scan_maximum_distance: 0.7
    link_match_minimum_response_fine: 0.95
    loop_match_minimum_response_fine: 0.95

    #minimum_travel_distance: 0.10
    #minimum_travel_heading: 0.10

    queue_size: 10000
    scan_buffer_size: 10000

