# Odometry System Parameters
arduino_to_odom_node:
  ros__parameters:
    # Timer frequency (Hz)
    update_rate: 20.0
    
    # Covariance values (adjust based on your sensor accuracy)
    position_covariance: 0.01
    orientation_covariance: 0.01
    velocity_covariance: 0.01
    
    # Debug options
    publish_tf: true
    debug_output: true
