# Joy node parameters
joy_node:
  ros__parameters:
    device_id: 0                    # Use device_id instead of device_name
    deadzone: 0.05                  # Keep current deadzone
    autorepeat_rate: 20.0           # Keep current rate  
    use_sim_time: false             # Keep current setting

# You can add other node parameters here if needed

